logger:
  path: logs/all.log
  max_bytes: 4194304    # 4mb
  backup_count: 5

reporter:
  base_url: https://wormhole.dcyy.cc/melina
  status_report_uri: /ca/status/report
  boot_plan_pick_uri: /ca/boot-plan/pick
  boot_record_report_uri: /ca/boot-record/report

dns:
  checked_domains:
    - route.home.lan
    - m.home.lan
    - www.baidu.com
    - cip.cc

samba:
  username: root
  password: 940103
  server_ip: 192.168.124.2
  port: 445

runes:
  device: /dev/sda
  directory: /root/runes