logger:
  path: logs/all.log
  max_bytes: 4194304    # 4mb
  backup_count: 5

reporter:
  base_url:
  status_report_uri:
  boot_plan_pick_uri:
  boot_record_report_uri:

dns:
  checked_domains:
    - route.home.lan
    - m.home.lan
    - www.baidu.com
    - cip.cc

samba:
  username: root
  password:
  server_ip: 192.168.124.2
  port: 445

runes:
  device: /dev/sda
  directory: /root/runes

lan_scanner:
  ip_range: 10.3.23.1/24
  known_devices:
    - mac: d2:4e:a7:e8:bc:4f
      name: Marika