logger:
  path: logs/all.log
  max_bytes: 4194304    # 4mb
  backup_count: 5

status_report_url: https://wormhole.dcyy.cc/melina/ca/status/report
restart_plan_pick_url: https://wormhole.dcyy.cc/melina/ca/boot-plan/pick
restart_record_report_url: https://wormhole.dcyy.cc/melina/ca/boot-record/report

dns:
  checked_domains:
    - route.home.lan
    - m.home.lan
    - www.baidu.com
    - cip.cc

samba:
  username: root
  password: 940103
  server_ip: 192.168.124.2
  port: 445

runes:
  device: /dev/sda
  directory: /root/runes